= Cancel Order Item

To cancel the order-item you will need to call `/cancelOrderItem` endpoint with post method. Further it cancel the record of OrderItem using cancelOrderItemInvResQty service.

== Properties
Following are the attributes used in below API:

[width="100%", cols="4" options="header"]
|=======
|Attribute |Type |Required| Description
|orderId|String|Yes|This attribute contains the unique ID of order in OMS.
|orderItemSeqId|String|No|This attribute contains the item ID of order in OMS.
|shipGroupSeqId|String|No|This attribute contains the unique ID of ship-group in OMS.
|cancelQuantity|BigDecimal|No|This attribute contains the quantity of item that you need to cancel.
|itemReasonMap|Map|No|This attribute contains the reason of cancellation. Accepts predefined values in the system.
|itemCommentMap|Map|No|This attribute contains the comment for cancelling the item.
|=======

=== *Request*
*Endpoint*
----
POST /api/cancelOrderItem HTTP/1.1

Host: example.com
----
*Headers*
----
Content-Type:​ application/json

Authorization: Bearer <token_value>

Accept: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "orderId":"NN11080",
    "orderItemSeqId":"00001"
}
----------------------------------------------------------------
=== *Response*

*Status Code*
----
HTTP/1.1​ ​200​ ​OK
----

*Headers*
----
Content-Type: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "orderItemSeqId":"00001",
    "cors.request.origin":<origin_URL>,
    "orderId":"NN11080",
    "cors.request.type":"actual",
    "webSiteId":"API"
}
----------------------------------------------------------------

To cancel the the order item in bulk you will need to call `/uploadJsonFile` endpoint with post method and MDM_CAN_ORD_ITM_JSON as configId. Further it use uploadAndImportFile service.

=== For more details please refer cancelOrderItem service:
link:../Services/cancelOrderItem.adoc[cancelOrderItem]
