= Check Preorder Items Inventory

To get the inventory count of a preorder item you will need to call the `/checkPreorderItemsInventory` endpoint with the GET method.

- If no productId/sku (string) is passed: All preorder items will be listed with available inventory.
- if no productStore is passed: All store items will be listed with available inventory

=== *User Story*

- It is used to get preOrder item inventory of all or any particular product store.

== Properties
Following are the attributes used in below API:
[width="100%", cols="3,2,10" options="header"]
|=======
|Attribute |Type |Description
|productId|String|Id of the product.
|sku|String|SKU of the product.
|productStore|String| Product Store Id.
|viewSize|Integer|Number of records to be shown (Default:10)
|=======

=== *Request*
*Endpoint*
----
GET /api/checkPreorderItemsInventory HTTP/1.1

Host: example.com
----
*Headers*
----
Content-Type:​ application/json

Accept: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
 "productId": "12222",
 "productStore": "SH_ECOM_STORE"
}
----------------------------------------------------------------
=== *Response*
Returns the inventory count for particular item if provided or returns all items.

*Status Code*
----
HTTP/1.1​ ​200 OK
----

*Headers*
----
Content-Type: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "count": "1",
    "docs": [
        {
            "productId": "12222",
            "sku": "42350352531709",
            "atp": 50,
            "qoh": 50
        }
    ]
}
----------------------------------------------------------------
