= Check Preorder Item

To check whether the item is preorder or not, you will need to call the `/isPreOrderItem` endpoint with the GET method.

Further it fetches the record from ShipmentAndItem entity based on following condition:

* productId: passed productId
* shipmentTypeId: PURCHASE_SHIPMENT
* statusId: PURCH_SHIP_CREATED
* estimatedArrivalDate: should be greater/equal to today's date.

.Following are the required attributes:

- productId/sku (required, string/List): Either productId or sku is required.

== Properties
Following are the attributes used in below API:
[width="100%", cols="5" options="header"]
|=======
|Attribute |IN |Type |Required |Description
|productId/sku |Query|String/List |Either productId/sku is required |Product's id/sku
|=======

=== *Request*
*Endpoint*
----
GET /api/isPreOrderItem HTTP/1.1

Host: example.com
----
*Headers*
----
Content-Type: application/json

Accept: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "productId": "12222"
}
----------------------------------------------------------------
=== *Response*
Returns the availability date for item.

*Status Code*
----
HTTP/1.1 200 OK
----

*Headers*
----
Content-Type: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
  isPreOrderItem: true
}
----------------------------------------------------------------
