= Update Order Item

To update the record of order-item you will need to call `/updateOrderItem` endpoint with post method. Further it updates the record in OrderItem entity using entity-auto.

.Following are the requried attributes:
- orderId (required, string): Unique identification of the order in the system.
- orderItemSeqId (required, string): Unique identification of the order item in the system.

=== *Request*
*Endpoint*
----
POST /api/updateOrderItem HTTP/1.1

Host: example.com
----
*Headers*
----
Content-Type:​ application/json

Authorization: Bearer <token_value>

Accept: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
For example: Update the promisedDate in orderItem

{
    "orderId": "NN11077"
    "orderItemSeqId": "00001"
    "promisedDatetime": "2022-03-11 23:59:59.999"
}
----------------------------------------------------------------
=== *Response*

*Status Code*
----
HTTP/1.1​ ​200​ ​OK
----

*Headers*
----
Content-Type: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "orderItemSeqId":"00001",
    "cors.request.origin":<origin_URL>,
    "orderId":"NN11077",
    "promisedDatetime":"2022-03-11 23:59:59.999",
    "cors.request.type":"actual","_EVENT_MESSAGE_":"Order Item updated successfully",
    "webSiteId":"API"
}
----------------------------------------------------------------

To update the the order item in bulk you will need to call `/uploadJsonFile` endpoint with post method and MDM_UPD_ORD_ITM_JSON as configId. Further it use uploadAndImportFile service.

=== For more details please refer updateOrderItem service:
link:../Services/updateOrderItem.adoc[updateOrderItem]
