= Change shipment item package

To change shipment item package you will need to call the `/moveShipmentItem` endpoint with the POST method. Further it uses deleteOrderShipmentItem service to remove item from old shipment and createOrderShipmentItem service to add item to the new shipment.

== Properties
Following are the attributes used in below API:

[width="100%", cols="4" options="header"]
|=======
|Attribute |Type |Required|Description
|shipmentId |String |Yes|Id of item's current shipment.
|toShipmentId |String |Yes|Shipment id in which item needs to move.
|shipmentPackageSeqId |String |Yes|Id of item's current shipment package.
|toShipmentPackageSeqId |String |Yes|Shipment package id in which item needs to move.
|shipmentItemSeqId |String |Yes|Shipment item id which needs to move.
|quantity |Integer |No|Quantity of item to move.
|=======

=== *Request*
*Endpoint*
----
POST /api/moveShipmentItem HTTP/1.1

----
*Headers*
----
Content-Type:​ application/json

Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1OTUzMTQ4OTEsInVzZXJMb2dpbklkIjoiYWFyb24ud2FnbmVyIn0.r2T1ER4mn1ljuilGi8Jr0OMqlD0Gd2OyzTT0Ah8kXPJLZssy1F-r5pRIC4OiyJbMQ_ZCESRxH1xBhlJcr3R3fw

Accept: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
       "shipmentId": "10440",
       "shipmentPackageSeqId": "00001",
       "shipmentItemSeqId":"00001",
       "toShipmentId":"10281",
       "toShipmentPackageSeqId":"00001",
       "quantity": 1
}
----------------------------------------------------------------
=== *Response*

*Status Code*
----
HTTP/1.1​ ​200 OK
----

*Headers*
----
Content-Type: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "shipmentId": "10440",
    "shipmentPackageSeqId": "00001",
    "shipmentItemSeqId": "00001",
    "toShipmentId": "10281",
    "toShipmentPackageSeqId": "00001",
    "quantity": 1,
    "webSiteId": "API"
}
----------------------------------------------------------------
