= Ready To Ship Orders

To get the list of ready to ship orders and order items for a particular store you will need to call `/readytoshiporders` endpoint with get method.


== Properties
Following are the attributes used in below API:

[width="100%", cols="3,2,10" options="header"]
|=======
|Attribute |Type |Description
|orderId |string |This attribute contains unique order ID.
|customerId |string |This attribute contains unique ID of the customer.
|customerName |string |This attribute contains customer name.
|picklistTotalItems |string |This attribute contains the count of picklist line items.
|picklistPickedItems |string |This attribute contains count of picked line items

For example:

A picklist have 3 items with 2 quantity each and picker picked 2 quantity of 1 line item, 1 quantity of 2nd line item and 0 quantity of 3rd line item then picklistPickedItems is 2.

|picklistPickedDate |string |This attribute contains picked date of the picklist.
|picklistId |string |This attribute contains unique ID of the picklist.
|pickerName |string |This attribute contains the name of the picker.
|facilityId |string |This attribute contains unique ID of the facility.
|shipmentId |string |This attribute contains unique ID of the shipment.
|items.orderItemSeqId |string |This attribute contains unique ID of the order item sequence.
|items.itemId |string |This attribute contains unique ID of the item.
|items.itemName |string |This attribute contains name of the order item.
|items.quantity |string |This attribute contains quantity of the order item.
|items.statusId |string |This attribute contains unique status ID of the order item.
|items.standardFeatures.productFeatureId |string |This attribute contains unique ID of the product feature.
|items.standardFeatures.description |string |This attribute contains description of the product feature.
|items.images.main.thumbnail |string |This attribute contains path of the thumbnail image.
|items.images.main.small |string |This attribute contains path of the small image.
|items.images.main.large |string |This attribute contains path of the large image.
|items.images.main.detail |string |This attribute contains path of the detail image.
|=======

.Following are the requried attributes:

- facilityId (required, string): The unique ID of the facility/warehouse.

=== *User Story*

- It is used to fetch list or orders ready to ship for a particular store.

=== *Request*
*Endpoint*
----
GET /api/readytoshiporders HTTP/1.1

Host: example.com
----

*Headers*
----
Content-Type:​ application/json

Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1NTE5NTIxNjcsInVzZXJMb2dpbklkIjoicGFsbGF2aUBleGFtcGxlLmNvbSJ9.VREDB8Mul9q4sdeNQAvhikVdpDJKKoMBfiBbeQTQOn5e5eOj6XdXnHNAguMpgXk8KXhj_scLDdlfe0HCKPp7HQ

Accept: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "sortBy":"createdDate",
    "sortOrder":"Desc",
    "viewSize":"10",
    "viewIndex":0,
    "facilityId":"STORE_1"
}
----------------------------------------------------------------
=== *Response*

*Status Code*
----
HTTP/1.1​ ​200​ ​OK
----

*Headers*
----
Content-Type: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "count" : "1", 
    "docs": [
        {
            "orderId" : "NN11142",
            "shipmentMethodTypeId" : "STOREPICKUP",
            "salesChannelEnumId" : "WEB_SALES_CHANNEL",
            "orderIdentifications" : [ "SHOPIFY_ORD_ID/4651072979197" , "SHOPIFY_ORD_NAME/#1351" , "SHOPIFY_ORD_NO/351" ],
            "customerId" : "10541",
            "customerName" : "Humera Khan",
            "picklistTotalItems": "0",
            "picklistPickedItems": "0",
            "picklistPickedDate": "",
            "picklistId": "",
            "pickerId": "",
            "pickerName": "",
            "facilityId" : "STORE_1",
            "shipmentId" : "10890",
            "items" : [
                {
                    "shipGroupSeqId" : "00001",
                    "orderItemSeqId" : "00001",
                    "itemId" : "12017",
                    "itemName": "Abominable Hoodie-L-Blue",
                    "brandName" : "HC Demo",
                    "quantity": "1",
                    "statusId" : "ITEM_APPROVED",
                    "standardFeatures": {
                        "COLOUR": { 
                            "productFeatureId": "10020",
                            "description": "Blue"
                        },
                        "SIZE": {
                            "productFeatureId": "TEXT_LARGE",
                            "description": "L"
                        }
                    },
                    "images": {
                        "main": {
                            "thumbnail": "https://cdn.shopify.com/s/files/1/0069/7384/9727/products/mh09-blue_main.jpg?v=1593170785",
                            "small": "https://cdn.shopify.com/s/files/1/0069/7384/9727/products/mh09-blue_main.jpg?v=1593170785",
                            "large": "https://cdn.shopify.com/s/files/1/0069/7384/9727/products/mh09-blue_main.jpg?v=1593170785",
                            "detail": "https://cdn.shopify.com/s/files/1/0069/7384/9727/products/mh09-blue_main.jpg?v=1593170785"
                        }
                    }
                }
            ]
        }
    ]
}
----------------------------------------------------------------
