= Reject Order Item

To reject order item you will need to call the `/rejectOrderItem` endpoint with the POST method. Accepts pre-defined attributes and rejects an item.

== Properties
Following are the attributes used in below API:

[width="100%", cols="4" options="header"]
|=======
|Attribute |Type |Required|Description
|orderId |String |Yes|This is the unique ID assigned to an order in the system.
|externalOrderId |String |No|This is the unique ID assigned to an order in the external system.
|orderIdentification |Object |No|This carry the identification information.
|orderIdentification.orderIdentificationTypeId |String |No|This is the identification type of the order in the system.
|orderIdentification.idValue |String |No|This is the identification value for the orderIdentificationTypeId.
|shipmentMethodTypeId  |String | No|This attribute contains shipment Method Type Id of item.
|orderItemSeqId |String |Yes|This attribute contains order item sequence ID.
|externalOrderItemId |String |No|This is the unique ID assigned to an order item in the external system.
|quantity |Integer |Yes|This attribute contains the quantity of product in the order.
|facilityId |String |Yes|This attribute contains facility/warehouse ID already exist in the system.
|externalFacilityId|String|No|FacilityID in the external system.
|recordVariance |String |No|Flag to record variance or not. Default value is Y
|rejectReason |String |No|Reason of rejection. Accepts predefined values in the system.
|=======

=== User Story
Reject desired item qty from a store/facility/warehouse if it is unfulfillable for any reason like unavailability, damaged, out of stock etc. It will also record variance for particular qty is requested by API.

.Following are the required attributes:

- orderId/externalId/orderIdentification (required, string): OrderId/externalId/orderIdentification is required.
- facilityId/externalFacilityId (required, string): Either facilityId/externalFacilityId is required.
- orderItemSeqId/externalOrderItemId (required, string): Either orderItemSeqId/externalOrderItemId is required.

=== *Request*
*Endpoint*
----
POST /api/rejectOrderItem HTTP/1.1

Host: example.com
----
*Headers*
----
Content-Type:​ application/json

Authorization: Bearer <token_value>

Accept: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "payload": {
      "facilityId": "STORE_1",
      "externalFacilityId": "DC_STORE_1",
      "shipmentMethodTypeId": "STOREPICKUP",
      "orderId": "NN11140",
      "externalOrderId": "",
      "orderIdentification": {
        "orderIdentificationTypeId": "SHOPIFY_ORD_ID",
        "idValue": "4651007475965	"
      },
      "orderItemSeqId": "00001",
      "externalOrderItemId": "11957901230333",
      "quantity": 1,
      "rejectReason": "NO_VARIANCE_LOG"
    }
}
----------------------------------------------------------------
=== *Response*

*Status Code*
----
HTTP/1.1​ ​201 CREATED

--or--

HTTP/1.1​ 400 Bad Request
----

*Headers*
----
Content-Type: application/json
----
*Body*
[source, json]
----------------------------------------------------------------
{
    "payload": {
      "facilityId": "STORE_1",
      "externalFacilityId": "DC_STORE_1",
      "shipmentMethodTypeId": "STOREPICKUP",
      "orderId": "NN11140",
      "externalOrderId": "",
      "orderIdentification": {
        "orderIdentificationTypeId": "SHOPIFY_ORD_ID",
        "idValue": "4651007475965	"
      },
      "orderItemSeqId": "00001",
      "externalOrderItemId": "11957901230333",
      "quantity": 1,
      "rejectReason": "NO_VARIANCE_LOG"
    }
}
----------------------------------------------------------------

=== For more details please refer rejectOrderItem Service:
link:../Services/rejectOrderItem.adoc[rejectOrderItem]
