= createOrdersFromShopify

This service is used to fetch the orders created in last set frequency(in minutes) and import them in OMS.

== Properties
Following are the attributes used in below service:

[width="100%", cols="4" options="header"]
|=======
|Attribute |Type |Required |Description
|frequency|Integer|Yes|To fetch orders created in last frequency (in minutes)
|shopifyConfigId|String|Yes|To fetch record as per the shopify configuration (SH_NN_CONFIG)
|=======

== Inline Services

=== importShopifyOrders
This service get the orders from shopify and pass the json list to uploadAndImportFile service, further it invokes the createShopifyOrder service for each json.

OrderItemAttributes is created for preorder item based on the following conditions:

* Checks the preorder item using isProductInPreorderCategory worker method.
* Checks the properties in the order-items list on the payload, its value can be preOrderProperty, backOrderProperty or storePickupProperty.
* Checks the SystemProperty configuration with systemResourceId as ShopifyServiceConfig and systemPropertyId as SH_NN_CONFIG.preorder.item.property.name
* If the conditions are staisfied with these checks then create the orderItemAttributes using PreOrderItemProperty as attrName, SH_NN_CONFIG.preorder.item.property.name as attrValue and Pre-order item property as attrDescription.
