== Q001. How does OMS make an item pre-orderable?


When a retailer wants to take pre-orders for an item, they need to provide certain information to OMS so that the system can add the item to the pre-order category and make the item pre-orderable.

There are two ways retailers can share this information with OMS. The first way is to share the details of the purchase order with OMS and the second way is for the retailer that does not maintain PO, these retailers can share the information of the item that should be made pre-orderable.

*For retailers with purchase orders details* +
If a retailer shares the details of the purchase order then the system automatically adds the item to the pre-order category if it fulfills the following conditions:

* Have zero inventory in all the stores and warehouses in OMS
* Have one or more ATP quantities in a PO with a future arrival date in OMS

If an item fulfills these two conditions then the system adds the item to the pre-order category when the *_loadPreorderCategoryItems_* service runs. 

Note: *_loadPreorderCategoryItems_* can be scheduled as per business requirements.

=== These are the technical details:
link:../Services/loadPreorderCategoryItems.adoc[loadPreorderCategoryItems]

+++<s>+++*For retailers without purchase orders details*+++</s>+++ +
+++<s>+++If a retailer does not deal with purchase orders then they can manually add the item to the pre-order category either using CSV or from UI.+++</s>+++

+++<s>+++In this case, as there will not be a purchase order for any item, the loadPreorderCategoryItems service will be disabled.+++</s>+++


=== These are the technical details to add the item to pre-order category via UI:
link:../Services/addCategoryProducts.adoc[addCategoryProducts]

=== These are the technical details to add the item to pre-order category via CSV:
link:../Services/importProductCategroyMember.adoc[importProductCategroyMember]

_Please note retailers can use only one of these ways, either share PO details or add items manually to the pre-order category. They cannot use both ways simultaneously. Also, they cannot use one way for some items and another way for other items., either all the pre-order items will be managed using PO, or all the pre-order items will be managed by manually adding them to the pre-order category._
